genome = "TCGTGGCTCTCATTTGCTGTGAAAAACTGCACAAAATTGGCGAACTGGATGACCATTTGATGCCAGTTGGGAAGGAGACTGTTAAATACGAGGAAGAGCTGGATTTACACGATGAAGAAGAGACCAGTGTTCCAGGAAGACCAGGTTCCACAAAACGAAGACAGTGCTACCCAAAAGCAATTCCAGAATGTTTGAGGGAGAGCTACCCCAGGCCCGGTCAGCCCTGTTACCTGTACGTGATCGGAATGGTCCTGACGACACCTTTACCTGATGAGCTCAACTTCAGAAGGCGGAAGCTCTACCCCCCTGAGGACACCACAAGATGCTTTGGAATACTGACAGCCAAGCCCATACCTCAGATCCCACACTTTCCTGTGTATACGCGCTCTGGAGAGGTGACCATATCTATTGAGTTGAAGAAGTCCGGCTTCACGTTATCTCTGCAAATGCTTGAGTTGATCACAAGGCTTCACCAGTATATATTCTCACATATTCTTCGGCTTGAAAAACCTGCACTAGAATTTAAACCCACAGACGCGGACTCAGCCTACTGCGTTCTACCTCTTAATGTTGTTAATGACTCCAGCACTTTGGACATTGACTTTAAATTCATGGAAGATATCGAGAAATCTGAAGCTCGCATAGGCATTCCCAGCACAAAGTATTCAAAAGAAACTCCCTTTGTTTTCAAATTAGAAGATTACCAAGATGCAGTTATCATTCCAAGATACCGCAATTTTGATCAGCCTCATCGATTTTATGTCGCTGACGTGTACACTGATCTTACCCCCCTGAGTAAATTTCCTTCCCCTGAGTATGAAACGTTTGCGGAGTATTACAAAACAAAGTATAACCTTGACCTGACCAATCTCAACCAGCCGCTGCTGGACGTGGACCACACGTCTTCACG"

A, T, G, C = 0, 0, 0, 0

length_genome = len(genome)
print(length_genome)

for base in genome:
    if base == "A":
        A += 1
    elif base == "T":
        T += 1
    elif base == "G":
        G += 1
    elif base == "C":
        C += 1

    else:
        Exception("This was not supposed to happen")

print("A T G C count: ", A, T, G, C)


start_codon = "ATG"

stop_codon_1 = "TAA"
stop_codon_2 = "TAG"
stop_codon_3 = "TGA"


for base in range(0, length_genome - 2):

    if genome[base: base+2] == start_codon:


